from __future__ import annotations

from datetime import date, datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import shlex
import shutil
import stat
from typing import Any, Mapping

from .activation_workspace import _load_activation_workspace
from .box_runtime import BoxRuntime
from .pilot_readiness import build_pilot_readiness_workpaper
from .pilot_shadow_series import (
    MAXIMUM_PERIODS,
    _load_pilot_shadow_period_archive,
    _period_number,
)


MANIFEST_NAME = "next-period-workspace-manifest.json"
COMMANDS_NAME = "commands.json"
ENV_NAME = "artifact-paths.env"
PERIOD_WORKSPACE_DIRECTORY = "pilot/period-workspaces"
DIRECTORIES = (
    "readiness",
    "handoff",
    "registrations",
    "shadow-baselines",
    "shadow-reports",
    "entity-reports",
    "portfolio",
    "observations",
    "runbook",
)
MAX_FILE_BYTES = 256 * 1024 * 1024
MAX_TOTAL_BYTES = 512 * 1024 * 1024
MAX_FILES = 1_000


class PilotShadowNextPeriodError(RuntimeError):
    """Raised when the next private Pilot Shadow period cannot be initialized."""


def _canonical_json_bytes(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def _sha256(body: bytes) -> str:
    return hashlib.sha256(body).hexdigest()


def _mkdir_private(path: Path) -> None:
    path.mkdir(mode=0o700)
    if os.name != "nt":
        path.chmod(0o700)


def _write_exclusive(path: Path, body: bytes) -> None:
    try:
        descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError as exc:
        raise PilotShadowNextPeriodError(
            f"next-period workspace file already exists: {path.name}"
        ) from exc
    try:
        if os.name != "nt":
            os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(body)
            stream.flush()
            os.fsync(stream.fileno())
    except Exception:
        path.unlink(missing_ok=True)
        raise


def _facts_as_of(value: str) -> str:
    text = str(value or "")
    try:
        parsed = date.fromisoformat(text)
    except ValueError as exc:
        raise PilotShadowNextPeriodError(
            "next-period facts_as_of must use YYYY-MM-DD"
        ) from exc
    if parsed.isoformat() != text:
        raise PilotShadowNextPeriodError(
            "next-period facts_as_of must use canonical YYYY-MM-DD"
        )
    return text


def _next_period(period: str) -> str:
    number = _period_number(period) + 1
    year, month_index = divmod(number, 12)
    return f"{year:04d}-{month_index + 1:02d}"


def _command(step_id: str, purpose: str, argv: list[str]) -> dict[str, Any]:
    return {
        "step_id": step_id,
        "purpose": purpose,
        "action": "run_cli",
        "argv": argv,
        "shell_preview": shlex.join(argv),
        "requires_operator_edit": any(
            "REPLACE_WITH_" in argument for argument in argv
        ),
        "command_executed": False,
    }


def _paths(
    activation_root: Path,
    period_root: Path,
    *,
    multi_entity: bool,
) -> dict[str, Path]:
    paths = {
        "OPC_TAX_APPLICABILITY_REVIEW_DIR": (
            activation_root / "tax" / "reviews"
        ),
        "OPC_TAX_APPLICABILITY_REGISTRY_RECEIPT": (
            activation_root / "tax" / "registry-receipt.json"
        ),
        "OPC_PILOT_READINESS_REVIEW": period_root / "readiness" / "reviewed.json",
        "OPC_PILOT_DATA_HANDOFF_REVIEW": period_root / "handoff" / "reviewed.json",
        "OPC_PILOT_SHADOW_RUN_REGISTRATION": (
            period_root / "registrations" / "run.json"
        ),
        "OPC_PILOT_SHADOW_OBSERVATION_REVIEW": (
            period_root / "observations" / "reviewed.json"
        ),
        "OPC_PILOT_SHADOW_ENTITY_REPORT_DIR": period_root / "entity-reports",
        "OPC_PILOT_SHADOW_SERIES_EVIDENCE_ROOT": (
            activation_root / "pilot" / "series-periods"
        ),
        "OPC_FINANCE_PIPELINE_RUNS_ROOT": activation_root / "pipeline-runs",
    }
    if multi_entity:
        paths["OPC_PILOT_SHADOW_PORTFOLIO_REVIEW"] = (
            period_root / "observations" / "portfolio-reviewed.json"
        )
    return paths


def _environment_body(paths: Mapping[str, Path]) -> bytes:
    lines = [
        "# Generated by opc-finance-box pilot-shadow-next-period-init.",
        "# Contains private artifact paths only; credentials remain in a secret manager.",
    ]
    for name in sorted(paths):
        lines.append(f"{name}={shlex.quote(str(paths[name]))}")
    lines.extend([
        "",
        "# This file does not authorize posting, payment, period close or filing.",
    ])
    return ("\n".join(lines) + "\n").encode("utf-8")


def _commands(
    runtime: BoxRuntime,
    config_path: Path,
    activation_root: Path,
    period_root: Path,
    *,
    period: str,
    facts_as_of: str,
) -> dict[str, Any]:
    readiness_workpaper = period_root / "readiness" / "workpaper.json"
    readiness_review = period_root / "readiness" / "reviewed.json"
    handoff_workpaper = period_root / "handoff" / "workpaper.json"
    handoff_review = period_root / "handoff" / "reviewed.json"
    registration = period_root / "registrations" / "run.json"
    observation_receipt = period_root / "observations" / "receipt.json"
    observation_review = period_root / "observations" / "reviewed.json"
    evidence_root = activation_root / "pilot" / "series-periods"
    runs_root = activation_root / "pipeline-runs"
    entity_reports = {
        entity_id: period_root / "entity-reports" / f"{entity_id}.json"
        for entity_id in sorted(runtime.entities.ids())
    }
    steps: list[dict[str, Any]] = [
        {
            "step_id": "pilot-readiness-complete",
            "purpose": "complete the exact next-period mappings and bounded read-only plan",
            "action": "edit_private_json",
            "relative_file": "readiness/workpaper.json",
            "requires_operator_edit": True,
            "command_executed": False,
        },
        _command(
            "pilot-readiness-review",
            "independently review the exact next-period readiness workpaper",
            [
                "opc-finance-box", "pilot-readiness-review", str(config_path),
                str(readiness_workpaper), "--actor",
                "REPLACE_WITH_PILOT_REVIEWER", "--rationale",
                "REPLACE_WITH_RATIONALE", "--evidence-reference",
                f"advisor://REPLACE_WITH_{period}_PILOT_REFERENCE", "--output",
                str(readiness_review),
            ],
        ),
        _command(
            "pilot-readiness-verify",
            "re-verify next-period readiness against the current tax rotation",
            [
                "opc-finance-box", "pilot-readiness-verify", str(config_path),
                str(readiness_review), "--tax-review-dir",
                str(activation_root / "tax" / "reviews"),
                "--tax-registry-receipt",
                str(activation_root / "tax" / "registry-receipt.json"),
                "--as-of", facts_as_of,
            ],
        ),
        _command(
            "data-handoff-init",
            "create a fresh period-bound controlled source-intake workpaper",
            [
                "opc-finance-box", "pilot-data-handoff-init", str(config_path),
                str(readiness_review), "--prepared-by",
                "REPLACE_WITH_HANDOFF_PREPARER", "--custodian-principal",
                "REPLACE_WITH_DATA_CUSTODIAN", "--as-of", facts_as_of,
                "--output", str(handoff_workpaper),
            ],
        ),
        {
            "step_id": "data-handoff-complete",
            "purpose": "complete current-period source inventory, custody and access evidence",
            "action": "edit_private_json",
            "relative_file": "handoff/workpaper.json",
            "requires_operator_edit": True,
            "command_executed": False,
        },
        _command(
            "data-handoff-review",
            "independently approve the exact current-period controlled intake",
            [
                "opc-finance-box", "pilot-data-handoff-review", str(config_path),
                str(handoff_workpaper), str(readiness_review), "--actor",
                "REPLACE_WITH_HANDOFF_REVIEWER", "--rationale",
                "REPLACE_WITH_RATIONALE", "--evidence-reference",
                f"review://REPLACE_WITH_{period}_HANDOFF_REFERENCE", "--as-of",
                facts_as_of, "--output", str(handoff_review),
            ],
        ),
        _command(
            "data-handoff-verify",
            "re-verify current-period controlled intake without exposing values",
            [
                "opc-finance-box", "pilot-data-handoff-verify", str(config_path),
                str(handoff_review), str(readiness_review), "--as-of", facts_as_of,
            ],
        ),
        {
            "step_id": "pipeline-attempts-complete",
            "purpose": "record and independently approve one current-period month-close attempt per entity",
            "action": "complete_external_prerequisite",
            "required_entity_ids": list(entity_reports),
            "requires_operator_edit": True,
            "command_executed": False,
        },
    ]
    registration_argv = [
        "opc-finance-box", "pilot-shadow-run-register", str(config_path),
        str(handoff_review), str(readiness_review),
    ]
    for entity_id in entity_reports:
        registration_argv.extend([
            "--entity-attempt", f"{entity_id}=REPLACE_WITH_REVIEWED_ATTEMPT_ID",
        ])
    registration_argv.extend([
        "--actor", "REPLACE_WITH_SHADOW_RUN_REGISTRAR", "--rationale",
        "REPLACE_WITH_RATIONALE", "--evidence-reference",
        f"workpaper://shadow/{period}/registration", "--as-of", facts_as_of,
        "--runs-root", str(runs_root), "--output", str(registration),
    ])
    steps.extend([
        _command(
            "shadow-run-register",
            "bind exactly one approved current-period attempt per legal entity",
            registration_argv,
        ),
        _command(
            "shadow-run-verify",
            "re-verify the current-period registration against the append-only run ledger",
            [
                "opc-finance-box", "pilot-shadow-run-verify", str(config_path),
                str(registration), str(handoff_review), str(readiness_review),
                "--runs-root", str(runs_root), "--as-of", facts_as_of,
            ],
        ),
    ])
    for entity_id, reviewed_report in entity_reports.items():
        baseline = period_root / "shadow-baselines" / f"{entity_id}.xlsx"
        comparison = period_root / "shadow-reports" / f"{entity_id}.json"
        steps.extend([
            _command(
                f"shadow-close-template:{entity_id}",
                "create a new human-close baseline workbook for this entity and period",
                [
                    "opc-finance-box", "shadow-close-template", str(config_path),
                    "--output", str(baseline),
                ],
            ),
            {
                "step_id": f"shadow-close-baseline-complete:{entity_id}",
                "purpose": "complete the independent human-close baseline for the exact entity and period",
                "action": "edit_private_workbook",
                "relative_file": f"shadow-baselines/{entity_id}.xlsx",
                "entity_id": entity_id,
                "period": period,
                "requires_operator_edit": True,
                "command_executed": False,
            },
            _command(
                f"shadow-close-compare:{entity_id}",
                "compare the human baseline with the deterministic entity result",
                [
                    "opc-finance-box", "shadow-close-compare", str(config_path),
                    str(baseline),
                    f"REPLACE_WITH_PRIVATE_FINANCE_RESULT_{entity_id}.json",
                    "--output", str(comparison),
                ],
            ),
            _command(
                f"shadow-close-review:{entity_id}",
                "independently review the exact entity comparison",
                [
                    "opc-finance-box", "shadow-close-review", str(config_path),
                    str(comparison), "--decision", "needs-correction", "--actor",
                    "REPLACE_WITH_ENTITY_SHADOW_REVIEWER", "--rationale",
                    "REPLACE_WITH_RATIONALE", "--evidence-reference",
                    f"review://REPLACE_WITH_{entity_id}_{period}_SHADOW_REFERENCE",
                    "--output", str(reviewed_report),
                ],
            ),
            _command(
                f"shadow-close-verify:{entity_id}",
                "verify the reviewed entity report without returning values",
                [
                    "opc-finance-box", "shadow-close-verify", str(config_path),
                    str(reviewed_report),
                ],
            ),
        ])
    portfolio_review: Path | None = None
    if len(entity_reports) > 1:
        portfolio_receipt = period_root / "portfolio" / "receipt.json"
        portfolio_review = period_root / "observations" / "portfolio-reviewed.json"
        portfolio_argv = [
            "opc-finance-box", "shadow-close-portfolio-assemble", str(config_path),
        ]
        for reviewed_report in entity_reports.values():
            portfolio_argv.extend(["--entity-report", str(reviewed_report)])
        portfolio_argv.extend([
            "--portfolio-result", "REPLACE_WITH_PRIVATE_PORTFOLIO_RESULT.json",
            "--output", str(portfolio_receipt),
        ])
        steps.extend([
            _command(
                "shadow-portfolio-assemble",
                "bind all reviewed entity reports to one ledger-verified portfolio",
                portfolio_argv,
            ),
            _command(
                "shadow-portfolio-review",
                "independently review the exact multi-entity portfolio scope",
                [
                    "opc-finance-box", "shadow-close-portfolio-review",
                    str(config_path), str(portfolio_receipt), "--decision",
                    "needs-correction", "--actor",
                    "REPLACE_WITH_PORTFOLIO_REVIEWER", "--rationale",
                    "REPLACE_WITH_RATIONALE", "--evidence-reference",
                    f"review://REPLACE_WITH_{period}_PORTFOLIO_REFERENCE",
                    "--output", str(portfolio_review),
                ],
            ),
            _command(
                "shadow-portfolio-verify",
                "verify the reviewed portfolio manifest without returning amounts",
                [
                    "opc-finance-box", "shadow-close-portfolio-verify",
                    str(config_path), str(portfolio_review),
                ],
            ),
        ])
    observation_assemble = [
        "opc-finance-box", "pilot-shadow-observation-assemble", str(config_path),
        str(registration), str(handoff_review), str(readiness_review),
    ]
    observation_verify = [
        "opc-finance-box", "pilot-shadow-observation-verify", str(config_path),
        str(observation_review), str(registration), str(handoff_review),
        str(readiness_review),
    ]
    archive = [
        "opc-finance-box", "pilot-shadow-period-archive", str(config_path),
        str(observation_review), str(registration), str(handoff_review),
        str(readiness_review),
    ]
    for reviewed_report in entity_reports.values():
        for argv in (observation_assemble, observation_verify, archive):
            argv.extend(["--entity-report", str(reviewed_report)])
    if portfolio_review is not None:
        for argv in (observation_assemble, observation_verify, archive):
            argv.extend(["--portfolio-review", str(portfolio_review)])
    observation_assemble.extend([
        "--runs-root", str(runs_root), "--as-of", facts_as_of,
        "--output", str(observation_receipt),
    ])
    observation_verify.extend([
        "--runs-root", str(runs_root), "--as-of", facts_as_of,
    ])
    archive.extend([
        "--evidence-root", str(evidence_root), "--runs-root", str(runs_root),
        "--as-of", facts_as_of,
    ])
    steps.extend([
        _command(
            "shadow-observation-assemble",
            "bind the current registration and every reviewed Shadow report",
            observation_assemble,
        ),
        _command(
            "shadow-observation-review",
            "independently review the exact current-period observation",
            [
                "opc-finance-box", "pilot-shadow-observation-review",
                str(config_path), str(observation_receipt), "--decision",
                "needs-correction", "--actor",
                "REPLACE_WITH_OBSERVATION_REVIEWER", "--rationale",
                "REPLACE_WITH_RATIONALE", "--evidence-reference",
                f"review://REPLACE_WITH_{period}_OBSERVATION_REFERENCE",
                "--output", str(observation_review),
            ],
        ),
        _command(
            "shadow-observation-verify",
            "re-verify the reviewed observation against all current source evidence",
            observation_verify,
        ),
        _command(
            "shadow-period-archive",
            "transactionally archive the verified period into the consecutive evidence root",
            archive,
        ),
        _command(
            "next-period-workspace-verify",
            "re-verify this private monthly workspace and its prior-period binding",
            [
                "opc-finance-box", "pilot-shadow-next-period-verify",
                str(config_path), str(activation_root), period, "--as-of",
                facts_as_of,
            ],
        ),
        _command(
            "period-runbook-status",
            "show resumable reported monthly progress without unlocking evidence gates",
            [
                "opc-finance-box", "pilot-shadow-period-runbook-status",
                str(config_path), str(activation_root), period,
            ],
        ),
        _command(
            "period-runbook-verify",
            "verify the append-only monthly progress chain and command bindings",
            [
                "opc-finance-box", "pilot-shadow-period-runbook-verify",
                str(config_path), str(activation_root), period,
            ],
        ),
        _command(
            "activation-workspace-status",
            "re-evaluate the first-customer activation state after period archival",
            [
                "opc-finance-box", "activation-workspace-status", str(config_path),
                str(activation_root), "--as-of", facts_as_of,
            ],
        ),
    ])
    return {
        "schema_version": 1,
        "artifact_type": "pilot_shadow_next_period_commands",
        "runtime_fingerprint": runtime.snapshot()["fingerprint"],
        "period": period,
        "previous_period": _previous_period(period),
        "steps": steps,
        "contains_credentials": False,
        "contains_financial_values": False,
        "commands_executed": False,
        "external_actions_performed": False,
    }


def _previous_period(period: str) -> str:
    number = _period_number(period) - 1
    if number < 0:
        raise PilotShadowNextPeriodError("next-period predecessor is invalid")
    year, month_index = divmod(number, 12)
    return f"{year:04d}-{month_index + 1:02d}"


def _period_parent(activation_root: Path) -> tuple[Path, bool]:
    parent = activation_root / PERIOD_WORKSPACE_DIRECTORY
    if parent.exists() or parent.is_symlink():
        if parent.is_symlink() or not parent.is_dir() or parent.resolve() != parent:
            raise PilotShadowNextPeriodError(
                "next-period workspace parent must be a real directory"
            )
        if os.name != "nt" and stat.S_IMODE(parent.stat().st_mode) != 0o700:
            raise PilotShadowNextPeriodError(
                "next-period workspace parent must use mode 0700"
            )
        return parent, False
    return parent, True


def _inspect_private_tree(root: Path) -> tuple[int, int]:
    directory_count = 0
    file_count = 0
    total_bytes = 0
    for path in root.rglob("*"):
        metadata = path.lstat()
        if stat.S_ISLNK(metadata.st_mode):
            raise PilotShadowNextPeriodError(
                "next-period workspace must not contain symbolic links"
            )
        if stat.S_ISDIR(metadata.st_mode):
            directory_count += 1
            if os.name != "nt" and stat.S_IMODE(metadata.st_mode) != 0o700:
                raise PilotShadowNextPeriodError(
                    "next-period workspace directories must use mode 0700"
                )
            continue
        if not stat.S_ISREG(metadata.st_mode):
            raise PilotShadowNextPeriodError(
                "next-period workspace may contain only regular files"
            )
        file_count += 1
        total_bytes += metadata.st_size
        if (
            file_count > MAX_FILES
            or metadata.st_size > MAX_FILE_BYTES
            or total_bytes > MAX_TOTAL_BYTES
        ):
            raise PilotShadowNextPeriodError(
                "next-period workspace exceeds its private file boundary"
            )
        if os.name != "nt" and stat.S_IMODE(metadata.st_mode) != 0o600:
            raise PilotShadowNextPeriodError(
                "next-period workspace files must use mode 0600"
            )
    return directory_count, file_count


def _read_json(path: Path, *, label: str) -> dict[str, Any]:
    if path.is_symlink() or not path.is_file():
        raise PilotShadowNextPeriodError(f"{label} must be a regular file")
    if path.stat().st_size <= 0 or path.stat().st_size > 2 * 1024 * 1024:
        raise PilotShadowNextPeriodError(f"{label} exceeds its size boundary")
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise PilotShadowNextPeriodError(f"{label} must contain valid JSON") from exc
    if not isinstance(value, dict):
        raise PilotShadowNextPeriodError(f"{label} must be a JSON object")
    return value


def initialize_next_pilot_shadow_period(
    runtime: BoxRuntime,
    config_path: str | Path,
    activation_root: str | Path,
    *,
    prepared_by: str,
    facts_as_of: str,
) -> dict[str, Any]:
    """Create the exact next monthly workspace after a verified archived period."""
    current_as_of = _facts_as_of(facts_as_of)
    root, activation_manifest, _, activation_verification = (
        _load_activation_workspace(runtime, activation_root)
    )
    config = Path(config_path).expanduser().resolve()
    if not config.is_file():
        raise PilotShadowNextPeriodError(
            "next-period Box config must be an existing regular file"
        )
    evidence_root = root / "pilot" / "series-periods"
    runs_root = root / "pipeline-runs"
    archived = _load_pilot_shadow_period_archive(
        runtime, evidence_root, runs_root, as_of=current_as_of,
    )
    latest = archived[-1]
    if archived[0]["period"] != activation_manifest["period"]:
        raise PilotShadowNextPeriodError(
            "archived period chain must start with the activation workspace period"
        )
    if not latest["ready_for_next_shadow_period"]:
        raise PilotShadowNextPeriodError(
            "latest archived Shadow observation is not ready for the next period"
        )
    if len(archived) >= MAXIMUM_PERIODS:
        raise PilotShadowNextPeriodError(
            "pilot Shadow archive reached its 24-period capacity"
        )
    period = _next_period(latest["period"])
    parent, parent_created = _period_parent(root)
    destination = parent / period
    if destination.exists() or destination.is_symlink():
        raise PilotShadowNextPeriodError(
            "next-period workspace already exists; refusing to overwrite"
        )
    entity_ids = sorted(runtime.entities.ids())
    paths = _paths(root, destination, multi_entity=len(entity_ids) > 1)
    readiness = build_pilot_readiness_workpaper(
        runtime, period=period, prepared_by=prepared_by,
    )
    readiness_body = _canonical_json_bytes(readiness)
    environment_body = _environment_body(paths)
    commands_body = _canonical_json_bytes(_commands(
        runtime,
        config,
        root,
        destination,
        period=period,
        facts_as_of=current_as_of,
    ))
    created = False
    try:
        if parent_created:
            _mkdir_private(parent)
        _mkdir_private(destination)
        created = True
        for relative in DIRECTORIES:
            _mkdir_private(destination / relative)
        initial_files = []
        for relative, body, kind, mutable in (
            (
                "readiness/workpaper.json", readiness_body,
                "mutable_period_readiness_workpaper", True,
            ),
            (ENV_NAME, environment_body, "immutable_private_path_contract", False),
            (COMMANDS_NAME, commands_body, "immutable_period_command_contract", False),
        ):
            _write_exclusive(destination / relative, body)
            initial_files.append({
                "relative_path": relative,
                "kind": kind,
                "mutable": mutable,
                "initial_sha256": _sha256(body),
            })
        manifest = {
            "schema_version": 1,
            "artifact_type": "pilot_shadow_next_period_workspace",
            "runtime_fingerprint": runtime.snapshot()["fingerprint"],
            "activation_workspace_manifest_sha256": activation_verification[
                "workspace_manifest_sha256"
            ],
            "first_archived_period": archived[0]["period"],
            "previous_archive_period_count": len(archived),
            "previous_period": latest["period"],
            "previous_observation_receipt_fingerprint": latest[
                "observation_receipt_fingerprint"
            ],
            "previous_source_bundle_fingerprint": latest[
                "source_bundle_fingerprint"
            ],
            "period": period,
            "facts_as_of": current_as_of,
            "created_at": datetime.now(timezone.utc).isoformat().replace(
                "+00:00", "Z"
            ),
            "prepared_by": prepared_by,
            "entity_ids": entity_ids,
            "directory_contract": list(DIRECTORIES),
            "initial_files": initial_files,
            "credentials_included": False,
            "raw_financial_source_files_copied": False,
            "commands_executed": False,
            "posting_authorized": False,
            "payment_authorized": False,
            "period_close_authorized": False,
            "external_filing_authorized": False,
            "external_actions_performed": False,
        }
        manifest_body = _canonical_json_bytes(manifest)
        _write_exclusive(destination / MANIFEST_NAME, manifest_body)
    except Exception:
        if created and destination.is_dir() and not destination.is_symlink():
            shutil.rmtree(destination)
        if parent_created and parent.is_dir() and not any(parent.iterdir()):
            parent.rmdir()
        raise
    return {
        "schema_version": 1,
        "initialized": True,
        "runtime_fingerprint": runtime.snapshot()["fingerprint"],
        "previous_period": latest["period"],
        "period": period,
        "entity_count": len(entity_ids),
        "multi_entity": len(entity_ids) > 1,
        "directory_count": len(DIRECTORIES),
        "initial_file_count": len(initial_files) + 1,
        "prior_archive_reverified": True,
        "new_period_readiness_template_created": True,
        "output_path_returned": False,
        "previous_archive_hashes_returned": False,
        "actors_returned": False,
        "credentials_included": False,
        "raw_financial_source_files_copied": False,
        "commands_executed": False,
        "posting_authorized": False,
        "payment_authorized": False,
        "period_close_authorized": False,
        "external_filing_authorized": False,
        "external_actions_performed": False,
    }


def verify_next_pilot_shadow_period(
    runtime: BoxRuntime,
    activation_root: str | Path,
    period: str,
    *,
    as_of: str | None = None,
) -> dict[str, Any]:
    """Verify one generated monthly workspace and its exact archived predecessor."""
    _period_number(period)
    current_as_of = _facts_as_of(as_of) if as_of is not None else None
    root, activation_manifest, _, activation_verification = (
        _load_activation_workspace(runtime, activation_root)
    )
    period_parent = root / PERIOD_WORKSPACE_DIRECTORY
    destination = period_parent / period
    if (
        period_parent.is_symlink()
        or not period_parent.is_dir()
        or period_parent.resolve() != period_parent
        or destination.is_symlink()
        or not destination.is_dir()
        or destination.resolve() != destination
    ):
        raise PilotShadowNextPeriodError(
            "next-period workspace must be an existing real derived directory"
        )
    if os.name != "nt" and (
        stat.S_IMODE(period_parent.stat().st_mode) != 0o700
        or stat.S_IMODE(destination.stat().st_mode) != 0o700
    ):
        raise PilotShadowNextPeriodError(
            "next-period workspace root and parent must use mode 0700"
        )
    directory_count, file_count = _inspect_private_tree(destination)
    manifest_path = destination / MANIFEST_NAME
    manifest = _read_json(manifest_path, label="next-period workspace manifest")
    expected_fields = {
        "schema_version", "artifact_type", "runtime_fingerprint",
        "activation_workspace_manifest_sha256", "first_archived_period",
        "previous_archive_period_count", "previous_period",
        "previous_observation_receipt_fingerprint",
        "previous_source_bundle_fingerprint", "period", "facts_as_of",
        "created_at", "prepared_by", "entity_ids", "directory_contract",
        "initial_files", "credentials_included",
        "raw_financial_source_files_copied", "commands_executed",
        "posting_authorized", "payment_authorized", "period_close_authorized",
        "external_filing_authorized", "external_actions_performed",
    }
    if set(manifest) != expected_fields:
        raise PilotShadowNextPeriodError(
            "next-period workspace manifest fields are invalid"
        )
    entity_ids = sorted(runtime.entities.ids())
    if (
        manifest.get("schema_version") != 1
        or manifest.get("artifact_type") != "pilot_shadow_next_period_workspace"
        or manifest.get("runtime_fingerprint") != runtime.snapshot()["fingerprint"]
        or manifest.get("activation_workspace_manifest_sha256")
        != activation_verification["workspace_manifest_sha256"]
        or manifest.get("first_archived_period") != activation_manifest["period"]
        or manifest.get("period") != period
        or manifest.get("previous_period") != _previous_period(period)
        or manifest.get("entity_ids") != entity_ids
        or manifest.get("directory_contract") != list(DIRECTORIES)
    ):
        raise PilotShadowNextPeriodError(
            "next-period workspace does not match the current Box or activation root"
        )
    _facts_as_of(str(manifest.get("facts_as_of") or ""))
    if current_as_of is not None and current_as_of < manifest["facts_as_of"]:
        raise PilotShadowNextPeriodError(
            "next-period reverification date must not predate initialization"
        )
    try:
        created_at = datetime.fromisoformat(
            str(manifest.get("created_at") or "").replace("Z", "+00:00")
        )
    except ValueError as exc:
        raise PilotShadowNextPeriodError(
            "next-period workspace created_at must be an ISO date-time"
        ) from exc
    if created_at.tzinfo is None:
        raise PilotShadowNextPeriodError(
            "next-period workspace created_at must include a timezone"
        )
    for field in (
        "credentials_included", "raw_financial_source_files_copied",
        "commands_executed", "posting_authorized", "payment_authorized",
        "period_close_authorized", "external_filing_authorized",
        "external_actions_performed",
    ):
        if manifest.get(field) is not False:
            raise PilotShadowNextPeriodError(
                f"next-period workspace manifest {field} must remain false"
            )
    for relative in DIRECTORIES:
        directory = destination / relative
        if directory.is_symlink() or not directory.is_dir():
            raise PilotShadowNextPeriodError(
                "next-period workspace required directory is missing"
            )
    initial_files = manifest.get("initial_files")
    if not isinstance(initial_files, list) or len(initial_files) != 3:
        raise PilotShadowNextPeriodError(
            "next-period workspace initial file contract is invalid"
        )
    expected_initial_contract = {
        "readiness/workpaper.json": (
            "mutable_period_readiness_workpaper", True,
        ),
        ENV_NAME: ("immutable_private_path_contract", False),
        COMMANDS_NAME: ("immutable_period_command_contract", False),
    }
    if {
        item.get("relative_path"): (item.get("kind"), item.get("mutable"))
        for item in initial_files if isinstance(item, dict)
    } != expected_initial_contract:
        raise PilotShadowNextPeriodError(
            "next-period workspace initial file scope changed"
        )
    for item in initial_files:
        if not isinstance(item, dict) or set(item) != {
            "relative_path", "kind", "mutable", "initial_sha256",
        }:
            raise PilotShadowNextPeriodError(
                "next-period workspace initial file entry is invalid"
            )
        relative = item.get("relative_path")
        if not isinstance(relative, str) or Path(relative).is_absolute():
            raise PilotShadowNextPeriodError(
                "next-period workspace initial file path is invalid"
            )
        candidate = (destination / relative).resolve()
        try:
            candidate.relative_to(destination)
        except ValueError as exc:
            raise PilotShadowNextPeriodError(
                "next-period workspace initial file escapes its root"
            ) from exc
        if not candidate.is_file() or candidate.is_symlink():
            raise PilotShadowNextPeriodError(
                "next-period workspace initial file is missing"
            )
        if item.get("mutable") is False and _sha256(
            candidate.read_bytes()
        ) != item.get("initial_sha256"):
            raise PilotShadowNextPeriodError(
                "next-period workspace immutable file changed"
            )
    readiness = _read_json(
        destination / "readiness" / "workpaper.json",
        label="next-period readiness workpaper",
    )
    if (
        readiness.get("runtime_fingerprint") != runtime.snapshot()["fingerprint"]
        or readiness.get("period") != period
        or readiness.get("prepared_by") != manifest.get("prepared_by")
        or readiness.get("contains_credentials") is not False
        or readiness.get("contains_raw_source_identifiers") is not False
        or readiness.get("contains_raw_tax_identifiers") is not False
        or readiness.get("contains_financial_values") is not False
        or readiness.get("external_actions_authorized") is not False
    ):
        raise PilotShadowNextPeriodError(
            "next-period readiness workpaper violates its private boundary"
        )
    expected_environment = _environment_body(_paths(
        root, destination, multi_entity=len(entity_ids) > 1,
    ))
    if (destination / ENV_NAME).read_bytes() != expected_environment:
        raise PilotShadowNextPeriodError(
            "next-period private path contract changed"
        )
    commands = _read_json(
        destination / COMMANDS_NAME, label="next-period command contract",
    )
    expected_commands = _commands(
        runtime,
        runtime.config_path.expanduser().resolve(),
        root,
        destination,
        period=period,
        facts_as_of=str(manifest["facts_as_of"]),
    )
    if commands != expected_commands:
        raise PilotShadowNextPeriodError(
            "next-period command contract changed from the current Box template"
        )
    prior_count = manifest.get("previous_archive_period_count")
    if not isinstance(prior_count, int) or not 1 <= prior_count <= MAXIMUM_PERIODS:
        raise PilotShadowNextPeriodError(
            "next-period predecessor archive coverage changed"
        )
    archive = _load_pilot_shadow_period_archive(
        runtime,
        root / "pilot" / "series-periods",
        root / "pipeline-runs",
        as_of=str(manifest["facts_as_of"]),
        period_count=prior_count,
    )
    if (
        len(archive) != prior_count
        or archive[0]["period"] != manifest["first_archived_period"]
    ):
        raise PilotShadowNextPeriodError(
            "next-period predecessor archive coverage changed"
        )
    predecessor = archive[prior_count - 1]
    if (
        predecessor["period"] != manifest["previous_period"]
        or predecessor["observation_receipt_fingerprint"]
        != manifest["previous_observation_receipt_fingerprint"]
        or predecessor["source_bundle_fingerprint"]
        != manifest["previous_source_bundle_fingerprint"]
        or not predecessor["ready_for_next_shadow_period"]
    ):
        raise PilotShadowNextPeriodError(
            "next-period predecessor no longer matches the verified archive"
        )
    return {
        "schema_version": 1,
        "valid": True,
        "runtime_fingerprint": runtime.snapshot()["fingerprint"],
        "previous_period": manifest["previous_period"],
        "period": period,
        "entity_count": len(entity_ids),
        "multi_entity": len(entity_ids) > 1,
        "directory_count": directory_count,
        "file_count": file_count,
        "prior_archive_reverified": True,
        "prior_archive_binding_current": True,
        "immutable_command_contract_current": True,
        "readiness_private_boundary_valid": True,
        "paths_returned": False,
        "previous_archive_hashes_returned": False,
        "actors_returned": False,
        "credentials_returned": False,
        "financial_values_returned": False,
        "commands_executed": False,
        "posting_authorized": False,
        "payment_authorized": False,
        "period_close_authorized": False,
        "external_filing_authorized": False,
        "external_actions_performed": False,
    }
